### ISSUE TITLE
What are supported video mix mode resolutions?

### ISSUE THREAD

**Issue by subsub** [AgoraIO/Basic-Recording#1]
I try to run the recording sample and it runs well. Only I have concern about the video resolution recorded that shows like a portrait video in a phone. So I try to change the video mix resolution to `width: 1280` and `height:720` to make it more like HD regular video. But when I start the recorder, it exit with error code 2 and stat_code 4.
When I check the log, there're these output which says video mix mode resolution is illegal:
```
video_recorder[23565]: (23565) /var/lib/jenkins/workspace/agora-release-linux/ServerSDK-Video/src/video_recorder/main.cpp:130: video recording wrapper:8, idle:300 write:5, read:6, live:0,channelid:2001 
video_recorder[23565]: (23565) /var/lib/jenkins/workspace/agora-release-linux/ServerSDK-Video/src/video_recorder/main.cpp:151: [ARS version] 79be5171ac5731ebb060e5e72512335ddb545ace
video_recorder[23565]: (23565) /var/lib/jenkins/workspace/agora-release-linux/ServerSDK-Video/src/video_recorder/main.cpp:153: uid 200 from vendor 77a35cc1724643be8c909f4a48457512 is joining channel 2001
video_recorder[23565]: (23565) /var/lib/jenkins/workspace/agora-release-linux/ServerSDK-Video/src/video_recorder/main.cpp:176: video mix mode resolution is illegal:ret=0x80, setting:(1280,720,15,500), mode:com

```
Thank you

**Comment by plutoless** [comment]
closing as it's too old issue. feel free to reopen if the problem still exists.

**Comment by Arcrueid** [comment]
I have the same problem.

On execute sdkdemo.js

` main.cpp:451: video mix mode resolution is illegal:ret=0x40, setting:(640,360,15,800), mode:com`

But trying the cpp example everything works ok.

**Comment by Arcrueid** [comment]
I have same problem.

occurs when setting the channelProfile to CHANNEL_PROFILE_COMMUNICATION

But everything works ok when running the cpp sample.

**Comment by plutoless** [comment]
when using recording, please ensure the channel profile matches with the one you use in your client
