### ISSUE TITLE
Unable to build Restful Recording NodeJs error

### ISSUE THREAD

**Issue by macymind** [AgoraIO/Basic-Recording#11]
I tried to build it but it gives many error with sdk and source code.
Agora Linux SDK build successful but this Restful Recording NodeJs build failed.

I have attached output of build.sh. Please check and help me on this issue.
[build error.txt](https://github.com/AgoraIO/Basic-Recording/files/3047428/build.error.txt)

**Comment by plutoless** [comment]
@macymind which version of recording sdk are you using?

**Comment by macymind** [comment]
Version 2.3.3

**Comment by macymind** [comment]
Latest one.
Thanks for quick response.

**Comment by plutoless** [comment]
guess some api has changed from 2.3.0 to 2.3.3. i'll do a quick adapt tonight.

**Comment by macymind** [comment]
May I get your 2.3.0 SDK?

**Comment by plutoless** [comment]
i don't have it in my laptop for the moment. if you just start integrating, latest version is also recommended.

**Comment by macymind** [comment]
Yeah but latest version is not working with your latest source. Today I need to release urgent build but it stuck at this position so I can't do it.

**Comment by plutoless** [comment]
i download 2.3.0 from our internal network and put it on release temporarily.
https://github.com/AgoraIO/Basic-Recording/releases/tag/2.3.0

Note this download will be removed after i fix 2.3.3 issue

**Comment by macymind** [comment]
Thanks for your kind help.
Let me test it and get back to you if I have any issues.

**Comment by macymind** [comment]
@plutoless 
That helped me!. But when I record a stream with sample app, recording is not playing and recording is not moved to "output" directory.

Here I am using broadcasting from android sdk.

**Comment by plutoless** [comment]
did it work for you before? i'm not quite clear about your business logic though. could you pls tell me the steps to reproduce your issue?

**Comment by macymind** [comment]
I just run your sample "sdkdemo.js" with my app id and channel name.

Current version Linux SDK demo is working fine. But when I try to record with your NodeJS demo, it continue recording but final mp4 file does not play.

Here I have attached my output for sdkdemo.js
[record error.txt](https://github.com/AgoraIO/Basic-Recording/files/3047737/record.error.txt)

**Comment by plutoless** [comment]
so you do have a mp4 file generated? which player are you using to play it?

**Comment by macymind** [comment]
Yes I have it. I am attaching 2 files for 2 different tries.
I have tried with VLC and QuickTime both

[Archive.zip](https://github.com/AgoraIO/Basic-Recording/files/3047762/Archive.zip)

**Comment by plutoless** [comment]
0_20190405111739794 this file works for me. and it seems it applies to NodeJS settings, if you directly record sth with linux sdk, you won't have green background as this is NodeJS transcoding configurations.
0_20190405112509530 this file does not work for me either.

Are you sure the first one is generated directly by linux sdk, while the second via nodejs?

**Comment by macymind** [comment]
No both files were recorded with nodejs

**Comment by plutoless** [comment]
for me the first file definitely play.
![image](https://user-images.githubusercontent.com/471561/55626641-a559e900-57de-11e9-81a8-b8ef0d9ae53a.png)

**Comment by macymind** [comment]
Which player is this?

**Comment by plutoless** [comment]
VLC on mac

**Comment by macymind** [comment]
Same here too. On mac

**Comment by macymind** [comment]
So how can I change input parameters in nodejs that is supplied to record sdk?

**Comment by plutoless** [comment]
i also tried again from my side and it works well. i'm not sure why your vlc is not working, the apparently the file is fine itself, otherwise i won't be able to play it.

Which parameter do you want to change? Not all parameters are exposed to js layer, if it's not available, you can change the config directly in c++ code, which is basically located at
https://github.com/AgoraIO/Basic-Recording/blob/664045b5516b29c251bebd03654b24ec73b631e4/Agora-Restful-Recording-Nodejs/record/src/agora_node_ext/agora_node_recording.cpp#L125

**Comment by macymind** [comment]
I changed mixedVideoAudio to MIXED_AV_CODEC_V2. And I can see video recorded. But with green background.
So now how can I resolve that green background issue?
Sorry for asking more questions but I am new to agora recording sdk.

**Comment by plutoless** [comment]
https://docs.agora.io/en/Recording/API%20Reference/recording_cpp/classagora_1_1recording_1_1_i_recording_engine.html#a4ac28b9e2342729c1b54400a5abb1d90
take a look at this setMixLayout api. the object is exposed to js layer, and it has a property called backgroundColor. You can see how this api is used in sdkdemo.js.

**Comment by plutoless** [comment]
2.3.3 has been supported. i've pushed the code. this issue is closed. in case of further issue, please open another one.
