### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by htrxuan** [AgoraIO/Basic-Recording#12]
Hi,
I cant setup it, could you help me?

![Screenshot at Apr 09 12-17-36](https://user-images.githubusercontent.com/795384/55775025-c01fac80-5ac1-11e9-8bc0-f56d4dcae63d.png)
![Screenshot at Apr 09 12-16-29](https://user-images.githubusercontent.com/795384/55775026-c01fac80-5ac1-11e9-885a-e5373f3e0487.png)

**Comment by plutoless** [comment]
The problem is as it stated: it cannot find sdk header file. Could you pls check the /src/sdk/include folder, and ensure IAgoraLinuxSdkCommon.h is there.

**Comment by htrxuan** [comment]
Thanks, I got it
