### ISSUE TITLE
Restful Recording Nodejs 调用 start 接口 报错

### ISSUE THREAD

**Issue by ouer1994** [AgoraIO/Basic-Recording#13]
Error: 101,with stat_code:1

**Comment by plutoless** [comment]
https://docs.agora.io/cn/Recording/the_error_native?platform=All%20Platforms
可以在这里查阅详细的错误代码，101的意思是appid没填对

**Comment by ouer1994** [comment]
@plutoless appid 确实是正确的, 是key参数传错了. 现在可以录制了,但是 录制完成 scp 下.mp4 文件, 使用 QuickTime Player 播放 什么画面都没有 , 黑屏. 使用 IINA 播放全屏都是绿色的, 也是没有画面

**Comment by ouer1994** [comment]
咨询了一下 你们的 小伙伴, 是因为我录制使用的是单流模式 需要转码, 但是我使用你们提供的py文件转码之后, 视频有声音, 但是 还是满屏绿色.

**Comment by plutoless** [comment]
用的是restful nodejs?restful nodejs默认是合流模式吧

**Comment by ouer1994** [comment]
是的 用的是 restful nodejs. 我也不是很清楚了( C++ 代码看不懂 ), 看了你们的文档 合流模式也需要使用py文件转码. 我如何自定义使用哪种模式呢

**Comment by ouer1994** [comment]
restful nodejs 默认是 合流 + 不实时转码模式录制 ? 如果是, 那么 这个视频我应该是直接可以看的对吗? 不需要 py 转码操作.

**Comment by plutoless** [comment]
合流+实时转码，视频也是在录完看的，但看到的可以是几路流通过规则合在一起的视频，按道理是可以直接看的

**Comment by ouer1994** [comment]
您的意思是 restful nodejs 默认是 合流 + 实时转码模式录制 ?

**Comment by plutoless** [comment]
是的

**Comment by ouer1994** [comment]
我说的直接看的意思是 录制完毕后 我把视频下载下来 使用 你们支持的播放器观看. 合流 + 不实时转码模式录制 生成的视频 可以下载下来直接观看吗

**Comment by ouer1994** [comment]
根据我的实际使用 你们是生成了一个 .mp4文件 和 一个.acc 文件 . 应该用的是 合流 + 不实时转码模式吧

**Comment by ouer1994** [comment]
您好 如果两个用户一对一视频, 其中一个挂断了, 我不调用 restful nodejs 的 stop 接口 录制的视频会出问题吗

**Comment by plutoless** [comment]
不会，他会自动退出

**Comment by ouer1994** [comment]
谢谢
