### ISSUE TITLE
How to extract thumbnail?

### ISSUE THREAD

**Issue by macymind** [AgoraIO/Basic-Recording#14]
Hello,

How can I extract recorded video thumbnail while recording?

**Comment by plutoless** [comment]
you can increase image capture interval.
The config can be adapted around here
https://github.com/AgoraIO/Basic-Recording/blob/f0f77da984ee2403792262368bf34ef520ff5b15/Agora-Restful-Recording-Nodejs/record/src/agora_node_ext/agora_node_recording.cpp#L126

**Comment by macymind** [comment]
Is there any possibility to get only one screenshot?

**Comment by plutoless** [comment]
the recording sdk also has it's raw video data api. then you will need to use that data to write to one image file yourself. via configuration there's no way for the moment.
