### ISSUE TITLE
How to set full layout?

### ISSUE THREAD

**Issue by htrxuan** [AgoraIO/Basic-Recording#15]
Hi,

I want to recording live broadcasting (only one streamer, all users are viewer - just watch streamer's video).

I try to record but layout not good. Could you help me? How to set full layout

Give me file to change all recording config. 

Thanks!

**Comment by plutoless** [comment]
https://github.com/AgoraIO/Basic-Recording/blob/release/2.3.3/Agora-Restful-Recording-Nodejs/record/sdkdemo.js
take a look at this file. Everything is in here, basically the idea is to use setMixedLayout to configure all streams layout

**Comment by htrxuan** [comment]
I set like this

 let rec = new AgoraRecordingSDK();
    let layout = {
        "canvasWidth": 1920,
        "canvasHeight": 1080,
        "backgroundColor": "#ffffff",
        "regions": []
    }

but still same

**Comment by plutoless** [comment]
take a look at userjoin + userleave event handles. It updates the regions field of layout.

**Comment by htrxuan** [comment]
Hi,
still same

here is my file: 

 let layout = {
        "canvasWidth": 1920,
        "canvasHeight": 1080,
        "backgroundColor": "#00ff00",
        "regions": []
    }

.......

rec.on("userjoin", function (uid) {
        //rearrange layout when new user joins
        console.log(`userjoin ${uid}`);
        let region = {
            "x": 0,
            "y": 0,
            "width": 1920,
            "height": 1080,
            "zOrder": 1,
            "alpha": 1,
            "uid": uid
        }

**Comment by plutoless** [comment]
This resolution is not supported.
To try out you can set canvas dimension to 640/480
and try to set the first user dimension to fill canvas

**Comment by htrxuan** [comment]
so, cant record with high resolution ? If this, it's so bad.

**Comment by htrxuan** [comment]
Possible like Tokbox: https://support.tokbox.com/hc/en-us/articles/360001669250-How-to-get-HD-resolution-recordings-and-live-streaming-in-Tokbox-sessions

1280x720 (HD)

**Comment by plutoless** [comment]
![image](https://user-images.githubusercontent.com/471561/55855757-f2e9a380-5b9a-11e9-85e3-a388c9dae4e1.png)
just realize 1920x1080 is in the support list, so it should be working. What do you see for above configs?

**Comment by htrxuan** [comment]
yep, but so how to config in this file? https://github.com/AgoraIO/Basic-Recording/blob/release/2.3.3/Agora-Restful-Recording-Nodejs/record/sdkdemo.js

I try to change resolution and background color, but all still same. Could you set a sample? My stream only one video, so need full and high resolution

**Comment by plutoless** [comment]
just want to know first what do you see in the recorded file when you use your configs.

**Comment by plutoless** [comment]
could you pls share a screenshot of recorded file which does not work?

**Comment by htrxuan** [comment]
Hi,

Need your help again
recordManager.js
 let layout = {
                    "canvasWidth": 1280,
                    "canvasHeight": 720,
                    "backgroundColor": "#ffffff",
                    "regions": []
                }
How to set video full width?
![Screenshot at Apr 25 11-15-43](https://user-images.githubusercontent.com/795384/56709438-869aa280-674b-11e9-814b-ad2413270803.png)

**Comment by anusornleo** [comment]
> ![image](https://user-images.githubusercontent.com/471561/55855757-f2e9a380-5b9a-11e9-85e3-a388c9dae4e1.png)
> just realize 1920x1080 is in the support list, so it should be working. What do you see for above configs?

If I want to record in vertical video. How I can set canvas?

**Comment by durveshparmar** [comment]
@anusornleo I have same issue. I am trying to go live in Mobile and Recording those videos which are showing on the left side. so Want to change the canvas resolution for vertical. Please let me know if you have found the solution for it. 

Thanks in advance
