### ISSUE TITLE
修改 config.channelProfile 不生效

### ISSUE THREAD

**Issue by ouer1994** [AgoraIO/Basic-Recording#17]
commit f0f77da984ee2403792262368bf34ef520ff5b15
adapt to 2.3.3

我们客户端使用的是 通信模式, restful nodejs 使用的是 直播模式, 录制的视频没有内容(满屏绿色), 当我修改了 Basic-Recording/Agora-Restful-Recording-Nodejs/record/src/agora_node_ext/agora_node_recording.cpp 文件中的 config.channelProfile 为直播模式(config.channelProfile = agora::linuxsdk::CHANNEL_PROFILE_COMMUNICATION;) 录制的视频依旧没有内容.

**Comment by ouer1994** [comment]
修改后 我又重新运行 build.sh 直接, 开始视频通话, 直接就报错了
![image](https://user-images.githubusercontent.com/23118182/56010716-57317200-5d17-11e9-851c-093a233a1963.png)

**Comment by plutoless** [comment]
两边的模式必须一致

**Comment by ouer1994** [comment]
明白明白, 感谢您的回答
