### ISSUE TITLE
云录制依赖文件找不到

### ISSUE THREAD

**Issue by sayiwen** [AgoraIO/Basic-Recording#19]
https://github.com/AgoraIO/Basic-Recording/blob/f0f77da984ee2403792262368bf34ef520ff5b15/Agora-Cloud-Recording-Nodejs/record/src/recorder_manager.h#L18

**Comment by plutoless** [comment]
这是云录制的头文件，云录制SDK放了吗？

**Comment by sayiwen** [comment]
就是找不到云录制SDK，不知道从哪儿下载

**Comment by plutoless** [comment]
如果有对应的客户支持群 可以问下销售
