### ISSUE TITLE
Help me solve this error

### ISSUE THREAD

**Issue by htrxuan** [AgoraIO/Basic-Recording#22]
Hi,

Could you help me this error?

Before i can setup but now cant, I tried on 2 Centos server.

![Screenshot at May 19 01-07-42](https://user-images.githubusercontent.com/795384/57973394-9c118e00-79d2-11e9-8619-81050e4b6f6a.png)

**Comment by plutoless** [comment]
Try downgrading your nodejs version? I see lots of v8 parameter issues

**Comment by htrxuan** [comment]
so, what's the best node version for recording?

**Comment by plutoless** [comment]
Try 8.x or 9.x maybe. If the error persists, kindly upload your full build log

**Comment by plutoless** [comment]
It’s also recommended to use Ubuntu instead of centos if possible, as Ubuntu has been tested more

**Comment by htrxuan** [comment]
thanks, works fine after down nodejs version
