### ISSUE TITLE
Convert video tools 

### ISSUE THREAD

**Issue by htrxuan** [AgoraIO/Basic-Recording#23]
As Agora document:

"Using the Transcoding Script

Once recording is finished, use video_convert.py and ffmpeg to merge the recorded files (decompress the transcoding tool with the command line tar -xvf)"

How to auto convert to mp4 when finish live stream? Now I must do via command line (SSH and run command), but I think customer cant do it. So any suggestion in this case?

**Comment by plutoless** [comment]
i believe you are using Nodejs for recording. In this case just do your own logic to run the script via nodejs exec/spawn to execute bash command after recording is finished.

**Comment by htrxuan** [comment]
yep, works fine with child-process.

BTW, How to change name file (ex: 0_20190521165321144_av.mp4) to sid.mp4 (ex: 182d96b3-eff4-4368-9a7e-1e83c5a42b35.mp4)

**Comment by Komal2905** [comment]
> As Agora document:
> 
> "Using the Transcoding Script
> 
> Once recording is finished, use video_convert.py and ffmpeg to merge the recorded files (decompress the transcoding tool with the command line tar -xvf)"
> 
> How to auto convert to mp4 when finish live stream? Now I must do via command line (SSH and run command), but I think customer cant do it. So any suggestion in this case?

Can you provide how you use Transcoding Script.
after ruunning python video_convert.py -f 'PATH_TO_FOLDER', able to create .mp4 file with audio but all screen is green

**Comment by vincent3q** [comment]
python video_convert.py -f 'PATH_TO_FOLDER'  is ok . Is the video before transcoding can play ? or can you provide your video ? @Komal2905

**Comment by Komal2905** [comment]
@vincent3q  Video can play but with all blank screen. this is https://drive.google.com/open?id=1yK7O77PZfCgzihKMmYeAHuoU6qBA2o3S link for video.

**Comment by Komal2905** [comment]
@vincent3q  here https://drive.google.com/file/d/1pcbpcbSXphUbNSoVLNsFE1x_QJ5jPIgm/view?usp=sharing
I will follow this document and will check if it is working properly

**Comment by vincent3q** [comment]
@Komal2905 I'm so sorry for replying you so late.

Layout: { client ms: 0, canvas: { width: 640, height: 480, bgnd: 16776960 }, Regions: [ -**568360575**, x: 0, y: 0, width: 0.5, height: 0.5, alpha: 255, render_mode: 0, zorder: NotSet}]

This line in recording_sys.log showing the  mixing_layout info that you set in your code. **568360575** is peer's uid, but your peers has no this uid, so your recording video has no peer's picture.

**Comment by Komal2905** [comment]
@vincent3q ,Thank you. The problem was with channel profile and it is solved now
