### ISSUE TITLE
Error Running On-Premise-Recording-Nodejs examples

### ISSUE THREAD

**Issue by homerlex** [AgoraIO/Basic-Recording#25]
Running on Ubuntu 14.04 with node 8.9.4.

Running the `node  sdkdemo.js` yields the following: 
```
node sdkdemo.js 
setting mix layout...
joinChannel...
appliteDir /home/vagrant/vagrant-workspace/Basic-Recording/On-Premise-Recording-Nodejs/record/src/sdk/bin/
pRecording->m_agorasdk->createChannel return result:1
join channel Id: Channel1, with uid: 3845185687
channel joined Channel1 3845185687
leave channel with code:12
Error: 3,with stat_code:16
err 3 16
```

Similarly, when I run `node app.js` and hit the server I get this: 
```
setting mix layout...
joinChannel...
appliteDir /home/vagrant/vagrant-workspace/Basic-Recording/On-Premise-Recording-Nodejs/record/src/sdk/bin/
pRecording->m_agorasdk->createChannel return result:1
join channel Id: Channel12, with uid: 1948140253
recorder started a7b122d487f743b2aca4254854c4ee05 Channel12 3bf8b59f-aaa5-44ff-98b4-40d12bd2e057
leave channel with code:12
Error: 3,with stat_code:16
sdk stopped due to err code: 3 stat: 16
stop recorder a7b122d487f743b2aca4254854c4ee05 Channel12 3bf8b59f-aaa5-44ff-98b4-40d12bd2e057
releasing 3bf8b59f-aaa5-44ff-98b4-40d12bd2e057
leaveChannel...
```

**Comment by plutoless** [comment]
@homerlex you will need to join agora rtc channel and start some video broadcasting before you can record sth. error code 3 usually indicates you are trying to record an empty room

**Comment by homerlex** [comment]
I had joined the channel from a web browser (using the web SDK) before starting the recorder.   I'll try it again on Monday.

**Comment by homerlex** [comment]
FYI - I am getting recording files now.  The .acc files contain audio but the .mp4 files don't contain any video.  When I try to play the mp4 nothing plays but the recording time looks correct:  https://www.screencast.com/t/PCRl0vnn

**Comment by vincent3q** [comment]
@homerlex Maybe your player is not in our supported list，you can try VLC player. Our supported player list, refer to: 
https://docs.agora.io/en/Recording/API%20Reference/recording_cpp/namespaceagora_1_1linuxsdk.html#af8f3a6529f57ccfa3621014808d1283a

In the above link, you can see different mixed_codec_type has different supported players， and you can change mixed_codec_type in this page： 
**config.mixedVideoAudio = agora::linuxsdk::MIXED_AV_DEFAULT;**
https://github.com/AgoraIO/Basic-Recording/blob/release/2.3.3/On-Premise-Recording-Nodejs/record/src/agora_node_ext/agora_node_recording.cpp

**Comment by homerlex** [comment]
Yes, it does play in VLC.  Thanks for that.  How do I change the mixed_codec_type in the On-Premise-Recording-Nodejs example?

**Comment by vincent3q** [comment]
@homerlex 
https://github.com/AgoraIO/Basic-Recording/blob/release/2.3.3/On-Premise-Recording-Nodejs/record/src/agora_node_ext/agora_node_recording.cpp

In the above link , line 126:**config.mixedVideoAudio = agora::linuxsdk::MIXED_AV_DEFAULT;**

agora::linuxsdk::MIXED_AV_DEFAULT  means mixed_codec_type = 0;
agora::linuxsdk::MIXED_AV_CODEC_V1 means mixed_codec_type = 1;
agora::linuxsdk::MIXED_AV_CODEC_V2 menas mixed_codec_type = 2;

you can change this config, and recomile your project, then it will work,

**Comment by homerlex** [comment]
Thanks @vincent3q

**Comment by Komal2905** [comment]
> FYI - I am getting recording files now. The .acc files contain audio but the .mp4 files don't contain any video. When I try to play the mp4 nothing plays but the recording time looks correct: https://www.screencast.com/t/PCRl0vnn

Hey I got same problem. Can you provide solutions of your problem

**Comment by homerlex** [comment]
@Komal2905 - I did not make any changes.  I just found that the video worked in the VLC player.  I haven't gone any further than that at this point.

**Comment by Komal2905** [comment]
@homerlex  did you use python script for conversion? or made any changes in nodejs code
Actually I am downloading .mp4 file from ubuntu server to  Mac via filezilla

**Comment by homerlex** [comment]
@Komal2905 - No, I made no modifications to the code.  I did no conversion on the file.  Just grabbed the recording off my Ubuntu server and played it on my Windows machine with VLC.

**Comment by BSuryakumar** [comment]
I have same issue .please tell about how to solve this issue????
