### ISSUE TITLE
Video is blank

### ISSUE THREAD

**Issue by Komal2905** [AgoraIO/Basic-Recording#26]
Hi, Using this I am able to record/get .aac and and .mp4 file. But when I tried to play the video there is all black screen.
.aac file is working correctly.
when I run **python video_convert.py** , the converted .mp4 file has green background only.
I am playing video on VLC and QuickTime player on Mac

**Comment by plutoless** [comment]
you may find out the supported media player list here: https://docs.agora.io/en/faq/recording_player

**Comment by Komal2905** [comment]
QuickTime Player is supported, video is playing after running python code, audio is audible but can't see anything is video. am I missing something which is crucial?

I am storing video on my Linux server and then downloading it in my Mac FileZilla

**Comment by plutoless** [comment]
How did you start the recording? do you have log files？

**Comment by plutoless** [comment]
also if you can upload your recorded video file it also helps

**Comment by Komal2905** [comment]
https://drive.google.com/open?id=1yK7O77PZfCgzihKMmYeAHuoU6qBA2o3S here you can see recorded video. I have agorasdk.log file

**Comment by plutoless** [comment]
Could you pls also provide your step/code to record this file?

**Comment by Komal2905** [comment]
@plutoless  I am using NodeJS code version
and  I have added AppID and channel name in file
I am using iOS SDK on my iPhone device to start video call between two device.

and when both phone able to see videos, I am running AppID node sdkdemo.js on my server

**Comment by plutoless** [comment]
sry for late reply. do you remember the corresponding channel name and recording time? I can take a look at backend

**Comment by plutoless** [comment]
the video you provided - it seems the recording is successful, the reason you see yellow background is because sdkdemo.js set yellow background. So my guess is you have no user in that channel while recording, or your mixlayout setting is somehow wron

**Comment by Komal2905** [comment]
@plutoless  you are right, I have set yellow background. the channel name is agoratest. Also both user on different iOs device can see each other and communicate each other. Can you provide proper way which I need to set  mixlayout

**Comment by plutoless** [comment]
https://github.com/AgoraIO/Basic-Recording/blob/06411224b9d827478cd0153e459d8149aa47cf26/On-Premise-Recording-Nodejs/record/sdkdemo.js#L66
have you changed this line to use your own appid instead our test one?

**Comment by Komal2905** [comment]
@plutoless  Yes, I did

**Comment by plutoless** [comment]
do you still remember the timestamp when you did the recording?

**Comment by plutoless** [comment]
Bonanza/Studylive is this you?

**Comment by Komal2905** [comment]
@plutoless  no. But I will do all setup again and try it. and check if it working properly or not

**Comment by plutoless** [comment]
yes please. thx.

**Comment by Komal2905** [comment]
Can you provide what I need to do with mixlayout?

**Comment by plutoless** [comment]
if besides appid you didn't change anything in sdkdemo.js, it should work. so just setup and try again and let me check the backend.

**Comment by Komal2905** [comment]
hey @plutoless , I tried again which fresh project but same problem

**Comment by Komal2905** [comment]
@plutoless  yes correct. But for app we want Communication profile, so can't update anything in iOS/Android code.
then we left with change in  recording to use communication profile. How to do it?

**Comment by Komal2905** [comment]
@plutoless Is this issue related to TCP and UDP port?

**Comment by plutoless** [comment]
you need to change here and recompile to use communication profile for recording
https://github.com/AgoraIO/Basic-Recording/blob/79e73e080b46b3dd9a1de13668b99b4049401be4/On-Premise-Recording-Nodejs/record/src/agora_node_ext/agora_node_recording.cpp#L129

**Comment by Komal2905** [comment]
@plutoless  
I made changes in my iOS app and changed channel profile. This is working fine
