### ISSUE TITLE
./build.sh 报错

### ISSUE THREAD

**Issue by yangkuo1993** [AgoraIO/Basic-Recording#30]
CXX(target) Release/obj.target/agorasdk/agora_node_ext/AgoraSdk.o
In file included from ../agora_node_ext/AgoraSdk.cpp:10:
../sdk/include/IAgoraRecordingEngine.h:297:24: warning: field 'channelProfile' will be initialized after field 'isAudioOnly' [-Wreorder]
    RecordingConfig(): channelProfile(agora::linuxsdk::CHANNEL_PROFILE_COMMUNICATION),
                       ^
../sdk/include/IAgoraRecordingEngine.h:304:9: warning: field 'idleLimitSec' will be initialized after field 'appliteDir' [-Wreorder]
        idleLimitSec(300),
        ^
../sdk/include/IAgoraRecordingEngine.h:310:9: warning: field 'captureInterval' will be initialized after field 'decodeAudio' [-Wreorder]
        captureInterval(5),
        ^
../sdk/include/IAgoraRecordingEngine.h:311:9: warning: field 'decodeAudio' will be initialized after field 'decodeVideo' [-Wreorder]
        decodeAudio(agora::linuxsdk::AUDIO_FORMAT_DEFAULT_TYPE),
        ^
../sdk/include/IAgoraRecordingEngine.h:312:9: warning: field 'decodeVideo' will be initialized after field 'mixedVideoAudio' [-Wreorder]
        decodeVideo(agora::linuxsdk::VIDEO_FORMAT_DEFAULT_TYPE),
        ^
In file included from ../agora_node_ext/AgoraSdk.cpp:11:
In file included from ../agora_node_ext/AgoraSdk.h:13:
../sdk/include/base/atomic.h:4:5: error: function-like macro '__GNUC_PREREQ' is not defined
#if __GNUC_PREREQ(4, 6)
    ^
../sdk/include/base/atomic.h:8:7: error: function-like macro '__GNUC_PREREQ' is not defined
#elif __GNUC_PREREQ(4, 4)
      ^
../sdk/include/base/atomic.h:65:2: error: "version should be at least 4.4"
#error "version should be at least 4.4"
 ^
In file included from ../agora_node_ext/AgoraSdk.cpp:11:
../agora_node_ext/AgoraSdk.h:138:9: error: unknown type name 'atomic_bool_t'; did you mean 'std::atomic_bool'?
        atomic_bool_t m_stopped;
        ^~~~~~~~~~~~~
        std::atomic_bool
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/atomic:1833:36: note: 'std::atomic_bool' declared here
typedef atomic<bool>               atomic_bool;
                                   ^
In file included from ../agora_node_ext/AgoraSdk.cpp:12:
In file included from ../agora_node_ext/node_async_queue.h:24:
../agora_node_ext/node_log.h:37:9: warning: 'LOG_WARNING' macro redefined [-Wmacro-redefined]
#define LOG_WARNING(format, ...) log(LOG_LEVEL_WARNING, format, ##__VA_ARGS__)
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/syslog.h:82:9: note: previous definition is here
#define LOG_WARNING     4       /* warning conditions */
        ^
In file included from ../agora_node_ext/AgoraSdk.cpp:12:
In file included from ../agora_node_ext/node_async_queue.h:24:
../agora_node_ext/node_log.h:42:9: warning: 'LOG_INFO' macro redefined [-Wmacro-redefined]
#define LOG_INFO(format, ...) log(LOG_LEVEL_INFO, format, ##__VA_ARGS__)
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/syslog.h:84:9: note: previous definition is here
#define LOG_INFO        6       /* informational */
        ^
../agora_node_ext/AgoraSdk.cpp:383:26: warning: comparison of integers of different signs: 'int' and 'unsigned int' [-Wsign-compare]
        for(int i = 0; i < speakerNumber; i++) {
                       ~ ^ ~~~~~~~~~~~~~
../agora_node_ext/AgoraSdk.cpp:401:26: warning: comparison of integers of different signs: 'int' and 'unsigned int' [-Wsign-compare]
        for(int i = 0; i < speakerNum; i++) {
                       ~ ^ ~~~~~~~~~~
9 warnings and 4 errors generated.
make: *** [Release/obj.target/agorasdk/agora_node_ext/AgoraSdk.o] Error 1

**Comment by plutoless** [comment]
our recording sdk does not support macos. you have to run & compile it on a linux server.
