### ISSUE TITLE
build.sh error

### ISSUE THREAD

**Issue by hongminjae** [AgoraIO/Basic-Recording#33]
I ran build.sh and got an error.

node js version: v10.16.0
Installed sdk version: 3.0.0

1 ... / agora_node_ext / AgoraSdk.h: 14: 10: fatal error: base / log.h: No such file or directory
 #include "base / log.h"
          ^ ~~~~~~~~~~~

=> The first error is that there is no base / log.h file. I arbitrarily added an empty file log.h.

2. The second error is shown below. 

How can I resolve these two errors?
I would appreciate it if you could answer me.

---------------------error log-------------------------------

gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@10.16.0 | linux | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@10.16.0 | linux | x64
gyp info find Python using Python version 3.7.4 found at "/usr/local/bin/python3"
gyp http GET https://nodejs.org/download/release/v10.16.0/node-v10.16.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v10.16.0/node-v10.16.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v10.16.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v10.16.0/SHASUMS256.txt
gyp info spawn /usr/local/bin/python3
gyp info spawn args [ '/usr/local/node-v10.16.0-linux-x64/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/sls4/dev/On-Premise-Recording-Nodejs/record/src/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/node-v10.16.0-linux-x64/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.cache/node-gyp/10.16.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/10.16.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/node-v10.16.0-linux-x64/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/10.16.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/sls4/dev/On-Premise-Recording-Nodejs/record/src',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@10.16.0 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/sls4/dev/On-Premise-Recording-Nodejs/record/src/build'
  CXX(target) Release/obj.target/agorasdk/agora_node_ext/AgoraSdk.o
../agora_node_ext/AgoraSdk.cpp: In member function 'void agora::AgoraSdk::onAudioVolumeIndication_node(const agora::linuxsdk::AudioVolumeInfo*, unsigned int)':
../agora_node_ext/AgoraSdk.cpp:383:26: warning: comparison of integer expressions of different signedness: 'int' and 'unsigned int' [-Wsign-compare]
         for(int i = 0; i < speakerNumber; i++) {
                        ~~^~~~~~~~~~~~~~~
../agora_node_ext/AgoraSdk.cpp: In member function 'virtual void agora::AgoraSdk::onAudioVolumeIndication(const agora::linuxsdk::AudioVolumeInfo*, unsigned int':
../agora_node_ext/AgoraSdk.cpp:401:26: warning: comparison of integer expressions of different signedness: 'int' and 'unsigned int' [-Wsign-compare]
         for(int i = 0; i < speakerNum; i++) {
                        ~~^~~~~~~~~~~~
  CXX(target) Release/obj.target/agorasdk/agora_node_ext/agora_node_recording.o
In file included from ../agora_node_ext/agora_node_recording.cpp:3:
../agora_node_ext/agora_node_recording.h:62:52: warning: backslash and newline separated by space
         #define napi_get_native_this(args, native) \
                                                     
../agora_node_ext/agora_node_recording.cpp:13: warning: "NODE_UID_TYPE" redefined
 #define NODE_UID_TYPE
 
In file included from ../agora_node_ext/agora_node_recording.h:6,
                 from ../agora_node_ext/agora_node_recording.cpp:3:
../agora_node_ext/node_uid.h:20: note: this is the location of the previous definition
 #define NODE_UID_TYPE int32
 
../agora_node_ext/agora_node_recording.cpp: In constructor 'agora::recording::NodeRecordingSdk::NodeRecordingSdk(v8::Isolate*)':
../agora_node_ext/agora_node_recording.cpp:59:39: error: invalid new-expression of abstract class type 'agora::AgoraSdk'
             m_agorasdk = new AgoraSdk();
                                       ^
In file included from ../agora_node_ext/agora_node_recording.h:7,
                 from ../agora_node_ext/agora_node_recording.cpp:3:
../agora_node_ext/./AgoraSdk.h:41:7: note:   because the following virtual functions are pure within 'agora::AgoraSdk':
 class AgoraSdk : virtual public agora::recording::IRecordingEngineEventHandler {
       ^~~~~~~~
In file included from ../agora_node_ext/./AgoraSdk.h:11,
                 from ../agora_node_ext/agora_node_recording.h:7,
                 from ../agora_node_ext/agora_node_recording.cpp:3:
../sdk/include/IAgoraRecordingEngine.h:63:18: note: 	'virtual void agora::recording::IRecordingEngineEventHandler::onRemoteVideoStreamStateChanged(uid_t, agora::linuxsdk::RemoteStreamState, agora::linuxsdk::RemoteStreamStateChangedReason)'
     virtual void onRemoteVideoStreamStateChanged(uid_t uid, linuxsdk::RemoteStreamState state, linuxsdk::RemoteStreamStateChangedReason reason) = 0;
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../sdk/include/IAgoraRecordingEngine.h:71:18: note: 	'virtual void agora::recording::IRecordingEngineEventHandler::onRemoteAudioStreamStateChanged(uid_t, agora::linuxsdk::RemoteStreamState, agora::linuxsdk::RemoteStreamStateChangedReason)'
     virtual void onRemoteAudioStreamStateChanged(uid_t uid, linuxsdk::RemoteStreamState state, linuxsdk::RemoteStreamStateChangedReason reason) = 0;
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../sdk/include/IAgoraRecordingEngine.h:173:18: note: 	'virtual void agora::recording::IRecordingEngineEventHandler::onRejoinChannelSuccess(const char*, uid_t'
     virtual void onRejoinChannelSuccess(const char* channelId, uid_t uid) = 0;
                  ^~~~~~~~~~~~~~~~~~~~~~
../sdk/include/IAgoraRecordingEngine.h:180:18: note: 	'virtual void agora::recording::IRecordingEngineEventHandler::onConnectionStateChanged(agora::linuxsdk::ConnectionStateType, agora::linuxsdk::ConnectionChangedReasonType)'
     virtual void onConnectionStateChanged(agora::linuxsdk::ConnectionStateType state, agora::linuxsdk::ConnectionChangedReasonType reason) = 0;
                  ^~~~~~~~~~~~~~~~~~~~~~~~
../sdk/include/IAgoraRecordingEngine.h:193:18: note: 	'virtual void agora::recording::IRecordingEngineEventHandler::onRemoteVideoStats(agora::linuxsdk::uid_t, const agora::linuxsdk::RemoteVideoStats&)'
     virtual void onRemoteVideoStats(agora::linuxsdk::uid_t uid, const agora::linuxsdk::RemoteVideoStats& stats) = 0;
                  ^~~~~~~~~~~~~~~~~~
../sdk/include/IAgoraRecordingEngine.h:206:18: note: 	'virtual void agora::recording::IRecordingEngineEventHandler::onRemoteAudioStats(agora::linuxsdk::uid_t, const agora::linuxsdk::RemoteAudioStats&)'
     virtual void onRemoteAudioStats(agora::linuxsdk::uid_t uid, const agora::linuxsdk::RemoteAudioStats& stats) = 0;
                  ^~~~~~~~~~~~~~~~~~
../sdk/include/IAgoraRecordingEngine.h:212:18: note: 	'virtual void agora::recording::IRecordingEngineEventHandler::onRecordingStats(const agora::linuxsdk::RecordingStats&)'
     virtual void onRecordingStats(const agora::linuxsdk::RecordingStats& stats) = 0;
                  ^~~~~~~~~~~~~~~~
../sdk/include/IAgoraRecordingEngine.h:222:18: note: 	'virtual void agora::recording::IRecordingEngineEventHandler::onLocalUserRegistered(uid_t, const char*)'
     virtual void onLocalUserRegistered(uid_t uid, const char* userAccount) = 0;
                  ^~~~~~~~~~~~~~~~~~~~~
../sdk/include/IAgoraRecordingEngine.h:231:18: note: 	'virtual void agora::recording::IRecordingEngineEventHandler::onUserInfoUpdated(uid_t, const agora::linuxsdk::UserInfo&)'
     virtual void onUserInfoUpdated(uid_t uid, const agora::linuxsdk::UserInfo& info) = 0;
                  ^~~~~~~~~~~~~~~~~
../agora_node_ext/agora_node_recording.cpp: In static member function 'static void agora::recording::NodeRecordingSdk::setMixLayout(const v8::FunctionCallbackInfo<v8::Value>&)':
../agora_node_ext/agora_node_recording.cpp:200:79: warning: 'v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const' is deprecated: Use maybe version [-Wdeprecated-declarations]
                Local<Object> layoutData = args[0]->ToObject(args.GetIsolate());
                                                                              ^

In file included from /root/.cache/node-gyp/10.16.0/include/node/v8.h:26,
                 from /root/.cache/node-gyp/10.16.0/include/node/node.h:63,
                 from ../agora_node_ext/agora_node_recording.cpp:1:
/root/.cache/node-gyp/10.16.0/include/node/v8.h:2446:31: note: declared here
                 Local<Object> ToObject(Isolate* isolate) const);
                               ^~~~~~~~
/root/.cache/node-gyp/10.16.0/include/node/v8config.h:324:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../agora_node_ext/agora_node_recording.cpp: In static member function 'static void agora::recording::NodeRecordingSdk::release(const v8::FunctionCallbackInfo<v8::Value>&)':
../agora_node_ext/agora_node_recording.cpp:335:29: warning: unused variable 'status' [-Wunused-variable]
                 napi_status status = napi_ok;
                             ^~~~~~
In file included from /root/.cache/node-gyp/10.16.0/include/node/node.h:63,
                 from ../agora_node_ext/agora_node_recording.cpp:1:
/root/.cache/node-gyp/10.16.0/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]':
/root/.cache/node-gyp/10.16.0/include/node/node_object_wrap.h:84:78:   required from here
/root/.cache/node-gyp/10.16.0/include/node/v8.h:9502:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<node::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
                reinterpret_cast<Callback>(callback), type);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [agorasdk.target.mk:109: Release/obj.target/agorasdk/agora_node_ext/agora_node_recording.o] Error 1
make: Leaving directory '/home/sls4/dev/On-Premise-Recording-Nodejs/record/src/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/node-v10.16.0-linux-x64/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.15.0-88-generic
gyp ERR! command "/usr/local/node-v10.16.0-linux-x64/bin/node" "/usr/local/node-v10.16.0-linux-x64/bin/node-gyp" "build"
gyp ERR! cwd /home/sls4/dev/On-Premise-Recording-Nodejs/record/src
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok

**Comment by plutoless** [comment]
sorry the nodejs version is not yet adapted to latest recording sdk. i'm working on it now and hopefully will get it work by end of today.

**Comment by hongminjae** [comment]
@plutoless 
Thank you for answer. I'll wait.

**Comment by theguywithideas** [comment]
Facing the same issue at my end. I tried with Node version 8.9.1 as instructed in the documentation, but that didn't work. Can you please give me the recommended node.js version for the current code to work?

**Comment by plutoless** [comment]
@hongminjae @theguywithideas it's fixed. please pull master code and try again.

**Comment by goelanshul321** [comment]
@plutoless  how do i mange the layout mode in the composite recording?

**Comment by plutoless** [comment]
@goelanshul321 you can pass your layout config object to define how video shall be placed, by using width/height property of each uid config.

**Comment by goelanshul321** [comment]
@plutoless  ya thats fine but how do i use the vertical layout mentioned in the agora docs.Do i need to code that by myself or this sdk supports that?

**Comment by hongminjae** [comment]
@plutoless 

Thanks. build was successful.
But other error occurred while starting the recording..

I get the following error. (13 error code) What should I do?
The video call code runs on the front(using cdn) as in the video call example, and the record code runs on the back end as in the example.
Is this a problem?

-------- error log -------------------

setting mix layout...
joinChannel...
appliteDir /home/sls4/dev/recording/record/src/sdk/bin/
pRecording->m_agorasdk->createChannel return result:1
Error: 13,with stat_code:3
sdk stopped due to err code: 13 stat: 3
stop recorder b6457e9bb1234d07b7f96fe5a51670ef math 59336cf5-a00d-45e0-a549-edccd7f9daa7
/home/sls4/dev/recording/recordManager.js:155
            throw new Error('recorder not exists');
            ^

Error: recorder not exists
    at RecordManager.onCleanup (/home/sls4/dev/recording/recordManager.js:155:19)
    at AgoraRecordSdk.sdk.on (/home/sls4/dev/recording/recordManager.js:73:18)
    at AgoraRecordSdk.emit (events.js:203:15)
    at AgoraRecordSdk.EventEmitter.emit (domain.js:448:20)
    at Immediate.setImmediate (/home/sls4/dev/recording/record/AgoraRecordSdk.js:20:18)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)
Worker 3376 died.

**Comment by hongminjae** [comment]
@plutoless 

Thanks. The previous problem is solved.
But there was another problem.
An mp4 file with only sound recorded(black screen...) is created.
What should I do?
I attached log files.

[agorasdk.log](https://github.com/AgoraIO/Basic-Recording/files/4310530/agorasdk.log)
[recording_0.log](https://github.com/AgoraIO/Basic-Recording/files/4310531/recording_0.log)
[recording_sys.log](https://github.com/AgoraIO/Basic-Recording/files/4310532/recording_sys.log)

**Comment by plutoless** [comment]
@hongminjae check https://docs.agora.io/en/faq/recording_player for supported players to play your recorded video file.
@goelanshul321 yes you can code that yourself with JS code
