### ISSUE TITLE
build.sh error with nodejs 12.18.0

### ISSUE THREAD

**Issue by poojamalviya20** [AgoraIO/Basic-Recording#40]
build.sh command is working fine with nodejs version 10.19.0 , But build.sh command is not working with nodejs version 12.18.0 and I want to use this command with node 12 version so can you help me out with this.

**Comment by chpaulin** [comment]
Hi. Any news on this? I got the same error and got the information that the NodeJS module was not officially supported. I hope that we could get this running as it is a great extension of Agoras current offering for us that run Node backends.

**Comment by plutoless** [comment]
@chpaulin i'll try to adapt within this week.

**Comment by chpaulin** [comment]
> @chpaulin i'll try to adapt within this week.

Thanks. Really appreciate it 🙏

**Comment by plutoless** [comment]
https://github.com/AgoraIO/Basic-Recording/commit/1a3ef45dfb28b70679770755b0f26c11de316759
