### ISSUE TITLE
Can I change name of recorded video .mp4?

### ISSUE THREAD

**Issue by anusornleo** [AgoraIO/Basic-Recording#42]
After record. I want to get url to video file in nodejs. so I want a rename in my custom name to create url for player. But I can't find solution to change name by code. or if not, Can I get a path of video as response ( ex. http://localhost/media/0_156151516516516.mp4 )

I tried to change output_file varable in video_convert.py but not working

**Comment by plutoless** [comment]
@anusornleo hi unfortunately currently the recorded file name does not support renaming.

**Comment by anusornleo** [comment]
Thank you for response.
