### ISSUE TITLE
Not able to set layout mode

### ISSUE THREAD

**Issue by lavish0000** [AgoraIO/Basic-Recording#47]
I am not able to set layout mode to best fit layout i.e. 1, 
let layout = {
                    "canvasWidth": 1920,
                    "canvasHeight": 1080,
                    "layoutMode": 1,
                    "backgroundColor": "#ffffff",
                    "isMixingEnabled": 1,
                    "mixedVideoAudio": 2,
                    "regionCount": 2,
                    "regions": []
                    }

and these are my region settings

let region = {
                "x": 0,
                "y": 0,
                "width": 1920,
                "height": 1080,
                "zOrder": 1,
                "alpha": 1,
                "uid": uid
                }
                
  can you please help me with this.
  this is a video call between two, so, i want it to be recorded half area for first user and other half for other.
![Screenshot from 2021-01-22 18-28-09](https://user-images.githubusercontent.com/46993225/105493607-a0319b00-5cdf-11eb-876f-6e6dab06d4bd.png)

**Comment by plutoless** [comment]
it's very likely your x/y coordinates for regions are wrong. could you pls help provide your detail configuration?

**Comment by lavish0000** [comment]
`const AgoraRecordingSDK = require("../record/AgoraRecordSdk");
const path = require("path");
const fs = require("fs");
const uuidv4 = require('uuid/v4');
const recordingService = require("../services/recordingService");
const constants = require("../../../util/constants");
const recordingController = require("../controller/recordingController");
class RecordManager {
    constructor() {
        this.recorders = {};
        //initialize output folder
        const output = path.resolve(__dirname, "./output");
        if (!fs.existsSync(output)) {
            fs.mkdirSync(output);
        }
    }

    //find existing recorder
    find(sid) {
        return this.recorders[sid];
    }

    initStorage(appid, channel, sid) {
        return new Promise((resolve, reject) => {
            const storagePath = path.resolve(__dirname, `./output/${sid}`);
            fs.mkdir(storagePath, {
                recursive: true
            }, err => {
                if (err) {
                    throw err;
                }
                resolve(storagePath);
            });
        })
    }

    start(key, appid, channel) {
        return new Promise((resolve, reject) => {
            const sid = uuidv4();
            this.initStorage(appid, channel, sid).then(storagePath => {
                let sdk = new AgoraRecordingSDK();

                // let layout = {
                //     "canvasWidth": 640,
                //     "canvasHeight": 480,
                //     "backgroundColor": "#000000",
                //     "isMixingEnabled": 1,
                //     "mixedVideoAudio": 2,
                //     "regions": []
                // }
                let layout = {
                    "canvasWidth": 1920,
                    "canvasHeight": 1080,
                    "layoutMode": 1,
                    "backgroundColor": "#ffffff",
                    "isMixingEnabled": 1,
                    "mixedVideoAudio": 2,
                    "regionCount": 2,
                    "regions": []
                    }
                    
                    
                let recorder = {
                    appid: appid,
                    channel: channel,
                    sdk: sdk,
                    sid: sid,
                    layout: layout,
                    storagePath: storagePath
                };
                sdk.setMixLayout(layout);

                sdk.joinChannel(key || null, channel, 0, appid, storagePath).then(() => {
                    this.subscribeEvents(recorder);
                    this.recorders[sid] = recorder;
                    console.log(`recorder started ${appid} ${channel} ${sid}`)
                    resolve(recorder);
                }).catch(e => {
                    reject(e);
                });
            });
        });
    }

     subscribeEvents(recorder) {
        let {
            sdk,
            sid,
            appid,
            channel,
            storagePath
        } = recorder;
        sdk.on("error", async (err, stat) => {
            console.error(`sdk stopped due to err code: ${err} stat: ${stat}`);
            console.log(`stop recorder ${appid} ${channel} ${sid}`)
            //clear recorder if error received
            this.onCleanup(sid);
            const recording = await recordingService.getRecording({channel_name : channel});
            if (recording[0].uploading_status == constants.uploadingStatus.PENDING){
                recordingController.uploadStream({
                    recorder,
                    recording_id : recording[0].recording_id,
                    booking_id: recording[0].booking_id,
                });
            } 
        });
        sdk.on("userleave", async (uid) => {
            console.log(`user leave ${uid}`);
            //rearrange layout when user leaves

            let recorder = this.find(sid);

            if (!recorder) {
                console.error("no recorder found");
                return;
            }
            let {
                layout,
                channel
            } = recorder;
            layout.regions = layout.regions.filter((region) => {
                return region.uid !== uid
            })
            sdk.setMixLayout(layout);


            //if broadcaster leave
            // const recording = await recordingService.getRecording({channel_name : channel});
            //     this.onCleanup(sid);
            //     if (recording[0].uploading_status == constants.uploadingStatus.PENDING){
            //         recordingController.uploadStream({
            //             recorder,
            //             recording_id : recording[0].recording_id,
            //             booking_id: recording[0].booking_id,
            //         });
            //     } 
        });

        sdk.on("userjoin", (uid) => {
            //rearrange layout when new user joins
            console.log(`user join ${uid}`);
            // let region = {
            //     "x": 0,
            //     "y": 0,
            //     "width": 320,
            //     "height": 240,
            //     "zOrder": 1,
            //     "alpha": 1,
            //     "uid": uid
            // }
            let region = {
                "x": 0,
                "y": 0,
                "width": 1920,
                "height": 1080,
                "zOrder": 1,
                "alpha": 1,
                "uid": uid
                }
            let recorder = this.find(sid);

            if (!recorder) {
                console.error("no recorder found");
                return;
            }

            let {
                layout
            } = recorder;
            switch (layout.regions.length) {
                case 0:
                    region.x = 0;
                    region.y = 0;
                    break;
                case 1:
                    region.x = 320;
                    region.y = 0;
                    break;
                case 2:
                    region.x = 0;
                    region.y = 240;
                    break;
                case 3:
                    region.x = 320;
                    region.y = 240;
                default:
                    break;
            }
            layout.regions.push(region)
            sdk.setMixLayout(layout);

        });
    }

    stop(sid) {
        let recorder = this.recorders[sid];
        if (recorder) {
            let {
                appid,
                channel
            } = recorder;
            console.log(`stop recorder ${appid} ${channel} ${sid}`)
            this.onCleanup(sid);
            return recorder;
        } else {
            throw new Error('recorder not exists');
        }
    }

    onCleanup(sid) {
        let recorder = this.recorders[sid];
        if (recorder) {
            let {
                sdk
            } = recorder;
            console.log(`releasing ${sid}`)
            sdk.leaveChannel()
            sdk.release()
            if (this.recorders[`${sid}`]) {
                delete this.recorders[`${sid}`];
            }
        } else {
            throw new Error('recorder not exists');
        }
    }
}



module.exports = new RecordManager();`

**Comment by lavish0000** [comment]
this is my record manager. @plutoless

**Comment by lavish0000** [comment]
is this what you were asking ?

**Comment by plutoless** [comment]
@lavish0000 
it seems you want to make one uid fill the whole canvas, in this case you need to comment out following code

```
        switch (layout.regions.length) {
            case 0:
                region.x = 0;
                region.y = 0;
                break;
            case 1:
                region.x = 320;
                region.y = 0;
                break;
            case 2:
                region.x = 0;
                region.y = 240;
                break;
            case 3:
                region.x = 320;
                region.y = 240;
            default:
                break;
        }
```

and you should not push new region to regions array, you should replace it with a new array with new region, say

```
layout.regions = [region]
```

**Comment by lavish0000** [comment]
ok, thanks. It works.
Could you please help me with one more thing, i.e right now i am sending width and height in layout. But is it possible that it could just automatically pick up the device width and height in which video is recorded , we don't have to set width and height manually.
`let layout = {
                "canvasWidth": 1920,
                "canvasHeight": 1080,
                "layoutMode": 1,
                "backgroundColor": "#ffffff",
                "isMixingEnabled": 1,
                "mixedVideoAudio": 2,
                "regionCount": 2,
                "regions": []
                }`

**Comment by plutoless** [comment]
no. video rendered on your device is just render dimension, it's different from capture dimension and send dimension. and there's no way for recording process to know what your device render dimension is.

**Comment by lavish0000** [comment]
ok, got it. Thanks.
