### ISSUE TITLE
Upload to 3rd party cloud storage

### ISSUE THREAD

**Issue by lavish0000** [AgoraIO/Basic-Recording#48]
Can we upload recording directly to a 3rd party cloud storage(cloudinary in this case) instead locally ?
Right now recording is stored in local path and then i upload it to a cloud storage.

**Comment by yoreland** [comment]
Did you check this link?
https://docs.agora.io/en/cloud-recording/cloud_recording_rest?platform=RESTful
Currently Agora Cloud Recording supports Amazon S3, Alibaba Cloud, Tencent Cloud and Qiniu Cloud.

**Comment by lavish0000** [comment]
ok, so for this i have to shift to cloud recording right ?
is their any other way to do the same thing through on premise recording ?
like right now , same chunks of TS/WebM are stored locally , is their a way to send them directly to cloud , instead of storing them locally.

**Comment by yoreland** [comment]
Yes.. but unfortunately, currently there is no API to directly integrate your OSS on local recording sdk. You may need to integrate OSS sync from your side

**Comment by lavish0000** [comment]
Okay got it. Thanks for the help. :+1:
