### ISSUE TITLE
Vertical Recording

### ISSUE THREAD

**Issue by andrezanna** [AgoraIO/Basic-Recording#55]
Hello, I'm recording vertically as this video will be used in an app.

I'm doing like this:

```recorder_local --appId APPID --channel CHANNEL --uid USER --channelProfile 1 --triggerMode 0 --idle 5 --isMixingEnabled 1 --layoutMode 0 --mixedVideoAudio 2 --mixResolution 405,720,10,1000 --appliteDir AGORA_BIN --channelKey TOKEN --recordFileRootDir RECORD_DIR --maxResolutionUid MAIN_USER --defaultVideoBg VIDEO_BG --defaultUserBg USER_BG ```

the problem is layout is not really good as I want the 2 video streams to split vertically the space.
I also tried with vertical layout or best-fit layout, but it split horizontally creating an awful effect.

Is there a way I can make it split vertically?
As you can see I'm using command line as I can't integrate c++ or java in my server. I'm using compiled c++ code.

Many thanks

**Comment by andrezanna** [comment]
@plutoless @sidsharma27 @PRWrl  can you please help me? Is there anything I can do?

**Comment by plutoless** [comment]
@andrezanna do you have a screenshot for what you tried?

**Comment by andrezanna** [comment]
Hello, I managed to solve it by switching to Java version. Many thanks
