### ISSUE TITLE
On-Premise Recording stop record unexpectedly

### ISSUE THREAD

**Issue by mahmuddin** [AgoraIO/Basic-Recording#56]
I have an issue when record successfully record the video stream, recorder unexpectedly and randomly stopped, but streaming is still continous. I have checked the error in pm2 but there is nothing error.  I confuse to re-produces this error start from where. When I record 1:30 minutes, the video recorded only 00:17 seconds even less than it. I create a new account, but the problem still exist. Perhaps I have reach 10.000 minutes limit every month, but when I check in agora console, the usage is not reach 10.000 minutes.

**Comment by plutoless** [comment]
do you recall the name of the channel which interrupted? and time

**Comment by mahmuddin** [comment]
channel: main
Call ID: 6434f6d18af4d5a678b8f498
Time: 12:57:37 to 12:59:59

**Comment by mahmuddin** [comment]
I try again with this:
-----------------------------------------
Channel:
 stream_1_3601298
Call ID:
6434fd3fee506fced92842af
Time:
13:25:03 to 13:25:42

but, the problem still exist

**Comment by plutoless** [comment]
are you using cloud recording? or on-premise one?

**Comment by mahmuddin** [comment]
on premise recording

**Comment by plutoless** [comment]
could you pls help provide the recording logs?

**Comment by plutoless** [comment]
it seems you are starting the recording successfully at least.

**Comment by mahmuddin** [comment]
@plutoless here is my agora-recording-out.log

setting mix layout...
joinChannel...
appliteDir /home/Basic-Recording-Agora/record/src/sdk/bin/
pRecording->m_agorasdk->createChannel return result:1
join channel Id: stream_1_2838180, with uid: 3852702650
User 592785590 joined, RecordingDir:/home/Basic-Recording-Agora/server/output/937a0c30-92a9-49fc-adc3-28c8f7c6da5b/
recorder started 02ada4792ea341afb95f6f7994c0a0e4 stream_1_2838180 937a0c30-92a9-49fc-adc3-28c8f7c6da5b
user join 592785590
setting mix layout...
color: #000000

agora-recording-error.log file is empty

**Comment by mahmuddin** [comment]
> it seems you are starting the recording successfully at least.

yes, it success successfully recorded, but not full length record. The last try I record 53s, but result only recorded 18 second. 


Channel: stream_1_2838180
Call ID: 64351252285a6a52235530b6
Time: 14:54:58 to 14:55:51

**Comment by mahmuddin** [comment]
![image](https://user-images.githubusercontent.com/5705941/231096140-65628166-4bc3-4858-9f29-030089ca4cc6.png)

**Comment by plutoless** [comment]
please help pack all your .log files under recording folder and attach here.

**Comment by mahmuddin** [comment]
[agora-recording-log.zip](https://github.com/AgoraIO/Basic-Recording/files/11198172/agora-recording-log.zip)

**Comment by plutoless** [comment]
<img width="826" alt="image" src="https://user-images.githubusercontent.com/471561/231105507-d186346c-4f1a-46e5-9a76-8e124ddad022.png">
according to the log, you are proactively leaving the channel. please double check if you are calling leave channel api somewhere.

**Comment by mahmuddin** [comment]
I have check the problem is with pm2 when running app.js
I run pm2 with this script:
pm2 start app.js --max-memory-restart 100 --name agora-recording
That caused calling leave channel proactively.

Thanks @plutoless

**Comment by mahmuddin** [comment]
Finnaly, I'm server the app like this:
pm2 start app.js -i max --name agora-recording --exp-backoff-restart-delay=100 --env production --max-memory-restart 300M
