### ISSUE TITLE
mozRTCPeerConnection is not defined

### ISSUE THREAD

**Issue by mahmuddin** [AgoraIO/Basic-Recording#57]
I have successfully recorded with On-Premise-Recording-Nodejs in Google Chrome. But I have face an error with Mozilla Firefox Developer Edition with version 113.0b2 (64-bit).

Error occurred in console like this:

**Uncaught ReferenceError: mozRTCPeerConnection is not defined.**

**Comment by plutoless** [comment]
@mahmuddin this more looks like a front-end error? when do you have this error? when playing the recording?

**Comment by mahmuddin** [comment]
@plutoless Ups, sorry I think this is related to front-end not recoding.
