### ISSUE TITLE
可以部署在内网吗

### ISSUE THREAD

**Issue by HeroBarry** [AgoraIO/Basic-Recording#8]
声网的sdk 是视频直播和语音可以部署与内网调用吗？需要将视频录制保存在内网中

**Comment by plutoless** [comment]
您好，因为要经过声网服务器所以纯内网录制是不可以的。

**Comment by HeroBarry** [comment]
在声网录制好再同步到内网有没有现成的处理方案，如果可以的话，怎么处理是高效和安全的

**Comment by vincent3q** [comment]
声网提供了cloud proxy做网络代理穿透，可以支持企业内网部署。

**Comment by HeroBarry** [comment]
感谢 正在落实相关方案细节 ，很给力啊@vincent3q
